**Examples: Lineal ALgebra and PyTorch** In PyTorch everything is a tensor.
                                                                                A tensor can represent:

A scalar → a single number

A vector → a list of numbers

A matrix → a table of numbers

Higher-dimensional data (used in Deep Learning)

In Deep Learning:

Scalars often represent biases, loss values, or learning rates

In [ ]:
import torch  # Import the PyTorch library

# --- Scalar tensors ---
# Create two scalar tensors (0-dimensional tensors)
x = torch.tensor(3.0)  # Scalar value 3.0
y = torch.tensor(2.0)  # Scalar value 2.0

# Element-wise addition of scalar tensors
sum_scalar = x + y

# Print the result
print(sum_scalar)

tensor(5.)


In Deep Learning:

Vectors often represent features, inputs, or weights

In [ ]:
# --- Vector tensors ---
# Create two 1D tensors (vectors)
a = torch.tensor([2.0, 3.0, 4.0])  # Vector a
b = torch.tensor([1.0, 2.0, 3.0])  # Vector b

# Element-wise vector addition
sum_vector = a + b

# Print the resulting vector
print(sum_vector)

tensor([3., 5., 7.])


torch.tensor(3.0) → scalar

torch.tensor([2.0, 3.0, 4.0]) → vector

PyTorch operations follow linear algebra rules

The same syntax scales to matrices, batches, and neural networks

In [ ]:
# Matrix Multiplication
A = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])   # Shape: (2 × 3)

B = torch.tensor([[1., 2.],
                  [3., 4.],
                  [5., 6.]])      # Shape: (3 × 2)

#B = torch.tensor([[4., 1., 1.],
#                  [2., 3., 4.]])   # Shape: (2 × 3)

# Matrix multiplication (A @ B)
C = A @ B
# C = A * B
# Print result
print(C)
print("Shape of result:", C.shape)

tensor([[22., 28.],
        [49., 64.]])
Shape of result: torch.Size([2, 2])


**A @ B it is matrix multiplication**

*   It follows the rules of linear algebra
*   It uses rows by columns

**A * B It multiplies element by element**

*   The matrices must have the same shape
*   It does NOT mix rows with columns




**Dot Product (Inner Product)**

The dot product is a fundamental operation in linear algebra that takes two vectors of the same length and returns a scalar.
It is defined as the sum of the element-wise products of the vector components.


In [ ]:
# --- Dot product (vector · vector) ---
a = torch.tensor([2.0, 3.0, 4.0])
b = torch.tensor([1.0, 2.0, 3.0])

dot_product = torch.dot(a, b)

print(dot_product)

tensor(20.)


We can think of the matrix product C = AB as computing Cᵢⱼ as the dot product between row i of A and column j of B.

In [ ]:
A = torch.tensor([[1., 2., 3],
                  [4., 5., 6]])  # rows = samples

B = torch.tensor([[1.],
                  [1.],
                  [1.]])        # column = weights

y = A @ B
print(y)

tensor([[ 6.],
        [15.]])


The Fundamental Operation: y = wx + b
In this notebook, we'll learn the most important mathematical operation in deep learning using a simple example: Should I buy this house?

Imagine you're house hunting and want to create a model that helps you decide whether to buy or not.

Input features (x):

Price (in thousands of dollars)
Size (in square meters)
Distance to work (in kilometers)
Output (y):

A number indicating how "good" the house is
If y > 0 → Buy ✅
If y < 0 → Don't buy ❌

In [1]:
import torch
import matplotlib.pyplot as plt

# Configuration for nice plots
plt.style.use('seaborn-v0_8-darkgrid')
plt.rcParams['figure.figsize'] = (10, 6)

print(f"PyTorch version: {torch.__version__}")
print(f"Device: {'GPU' if torch.cuda.is_available() else 'CPU'}")

PyTorch version: 2.9.0+cpu
Device: CPU


Let's break down each component:

x (input)
Tensor with the house features:

x = [price, size, distance]
w (weights)
Tensor indicating the importance of each feature:

w = [w_price, w_size, w_distance]
b (bias)
A number that adjusts the overall decision. It's like your "base budget" or "initial predisposition".

y (output)
The result of: y = w₁·x₁ + w₂·x₂ + w₃·x₃ + b

In [2]:
# Features of a house
price = 250.0      # $250,000
size = 120.0       # 120 m²
distance = 15.0    # 15 km from work

# Group them into a tensor
x = torch.tensor([price, size, distance])

print("🏠 House to evaluate:")
print(f"  Price: ${price:.0f},000")
print(f"  Size: {size:.0f} m²")
print(f"  Distance: {distance:.0f} km")
print(f"\n  Tensor x = {x}")
print(f"  Shape: {x.shape}")
print(f"  Type: {x.dtype}")

🏠 House to evaluate:
  Price: $250,000
  Size: 120 m²
  Distance: 15 km

  Tensor x = tensor([250., 120.,  15.])
  Shape: torch.Size([3])
  Type: torch.float32


In [3]:
# Define the WEIGHTS (w)
# These numbers represent the importance of each feature

w_price = -0.01      # HIGH price is bad → negative weight
w_size = 0.05        # LARGE size is good → positive weight
w_distance = -0.15   # LONG distance is bad → negative weight

w = torch.tensor([w_price, w_size, w_distance])

print("⚖️ Weights (importance of each feature):")
print(f"  w_price = {w_price} (negative because high price is bad)")
print(f"  w_size = {w_size} (positive because bigger is better)")
print(f"  w_distance = {w_distance} (negative because far is bad)")
print(f"\n  Tensor w = {w}")
print(f"  Shape: {w.shape}")

⚖️ Weights (importance of each feature):
  w_price = -0.01 (negative because high price is bad)
  w_size = 0.05 (positive because bigger is better)
  w_distance = -0.15 (negative because far is bad)

  Tensor w = tensor([-0.0100,  0.0500, -0.1500])
  Shape: torch.Size([3])


In [4]:
# Define the BIAS (b)
# It's a general adjustment, like your "predisposition to buy"

b = torch.tensor(2.0)  # A small positive bias (you're willing to buy)

print(f"📊 Bias (b) = {b.item()}")
print("  (A positive value means you have a predisposition to buy)")
print(f"  Type: {b.dtype}")

📊 Bias (b) = 2.0
  (A positive value means you have a predisposition to buy)
  Type: torch.float32


In [5]:
# STEP 1: Element-wise multiplication (w * x)
multiplication = w * x

print("STEP 1: Multiply each weight by its feature")
print("="*50)
print(f"w_price × price       = {w_price} × {price:.0f} = {multiplication[0].item():.2f}")
print(f"w_size × size         = {w_size} × {size:.0f} = {multiplication[1].item():.2f}")
print(f"w_distance × distance = {w_distance} × {distance:.0f} = {multiplication[2].item():.2f}")
print(f"\nResult: {multiplication}")

STEP 1: Multiply each weight by its feature
w_price × price       = -0.01 × 250 = -2.50
w_size × size         = 0.05 × 120 = 6.00
w_distance × distance = -0.15 × 15 = -2.25

Result: tensor([-2.5000,  6.0000, -2.2500])


In [6]:
# STEP 2: Sum all products (wx)
sum_wx = torch.sum(multiplication)

print("\nSTEP 2: Sum all products")
print("="*50)
print(f"{multiplication[0].item():.2f} + {multiplication[1].item():.2f} + {multiplication[2].item():.2f} = {sum_wx.item():.2f}")


STEP 2: Sum all products
-2.50 + 6.00 + -2.25 = 1.25


In [7]:
# STEP 3: Add the bias (wx + b)
y = sum_wx + b

print("\nSTEP 3: Add the bias")
print("="*50)
print(f"y = wx + b = {sum_wx.item():.2f} + {b.item()} = {y.item():.2f}")


STEP 3: Add the bias
y = wx + b = 1.25 + 2.0 = 3.25


In [8]:
# Final decision
print("\n" + "="*50)
print("🎯 FINAL RESULT")
print("="*50)
print(f"y = {y.item():.2f}")
print()

if y > 0:
    print("✅ DECISION: BUY THE HOUSE!")
    print(f"   (y = {y.item():.2f} > 0)")
else:
    print("❌ DECISION: DON'T BUY")
    print(f"   (y = {y.item():.2f} < 0)")


🎯 FINAL RESULT
y = 3.25

✅ DECISION: BUY THE HOUSE!
   (y = 3.25 > 0)


# TO DO

**Ejercicio 1 — Versión compacta con producto punto**
Reescribir el cálculo de y = w⋅x + b de forma compacta y demostrar que da el mismo resultado.


 **Ejercicios 2 — Cinco casas, varias características y decisión**

Calcular el score y para varias casas a la vez usando multiplicación matricial y luego tomar una decisión.

    [200., 150., 5.],   # House 1: Cheap, big, close
    [400., 100., 3.],   # House 2: Expensive, small, very close
    [250., 120., 15.],  # House 3: Medium price, medium size, far
    [180., 80., 25.],   # House 4: Cheap, small, very far
    [350., 180., 8.],   # House 5: Expensive, very big, medium distance


**Ejercicio 3 — Gráficas: contribuciones por característica y score final**


Visualizar:

1. cuánto aporta cada característica al score

2. el score final por casa y la decisión