<a href="https://colab.research.google.com/github/jdmartinev/ArtificialIntelligenceIM/blob/main/Lecture01/notebooks/L01_broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import torch

In [9]:
a = np.array([1.,2.,3.])

print(a.shape)

print(a.ndim)

print(a.dot(a))

print(a*a)

print(a.T@a)

print(a @ a.T)

(3,)
1
14.0
[1. 4. 9.]
14.0
14.0


In [12]:
b = torch.tensor([[1, 2, 3],[4, 5, 6]])
print(b)
print(b.shape)
print(b.ndim)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
2


In [16]:
b = torch.tensor([1., 2., 3.])
print(b)
print(b.dtype)
print(b.shape)
print(b.ndim)

print(b.matmul(b))
print(b.dot(b))
print(b @ b)

tensor([1., 2., 3.])
torch.float32
torch.Size([3])
1
tensor(14.)
tensor(14.)
tensor(14.)


In [21]:
c = torch.tensor([1., 2., 3.])
print(c.dtype)

c = torch.tensor([1., 2., 3.], dtype = torch.double)
print(c.dtype)

c = torch.tensor([1., 2., 3.], dtype = torch.float64)
print(c.dtype)

f = c.to(torch.float32)
print(f.dtype)



torch.float32
torch.float64
torch.float64
torch.float32


In [3]:
c = torch.tensor([1., 2., 3.])
print(c.device)

cpu


In [5]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
print(device)

d = c.to(device)
print(d.device)

cuda
cuda:0


In [6]:
e = d + c

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [7]:
!nvidia-smi

Mon Jul 14 16:58:46 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P0             26W /   70W |     120MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [5]:
a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

print(a + 1)

tensor([5., 7., 9.])
tensor([-3., -3., -3.])
tensor([ 4., 10., 18.])
tensor([0.2500, 0.4000, 0.5000])
tensor([2., 3., 4.])


In [7]:
X = torch.arange(6).view(2,3)
print(X)
w = torch.tensor([1,2,3])

tensor([[0, 1, 2],
        [3, 4, 5]])


In [9]:
z = X.matmul(w)
print(z)
print(z.shape)

tensor([ 8, 26])
torch.Size([2])


In [10]:
w = w.view(-1,1)
z = X.matmul(w)
print(z)
print(z.shape)

tensor([[ 8],
        [26]])
torch.Size([2, 1])


In [12]:
a = torch.tensor([[4],[5],[6]])
print(a.shape)

b = torch.tensor([7,8,9])
print(b.shape)

print(a + b)

torch.Size([3, 1])
torch.Size([3])
tensor([[11, 12, 13],
        [12, 13, 14],
        [13, 14, 15]])


In [17]:
X = torch.arange(6).view(2,3)
print(X)
print(X.shape)

w = torch.tensor([1,2,3])
print(w)
print(w.shape)

b = torch.tensor(2)
print(b.shape)

z = X.matmul(w) + b
print(z)
print(z.shape)



tensor([[0, 1, 2],
        [3, 4, 5]])
torch.Size([2, 3])
tensor([1, 2, 3])
torch.Size([3])
torch.Size([])
tensor([10, 28])
torch.Size([2])
